version: '3.4'

services:
  catalogdb:
    image: mongo:4.4.6

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogApi/Dockerfile
volumes:
  mongo_data: 